### ISSUE TITLE
This is a test issue

### ISSUE THREAD

**Issue by kensodemann** [kensodemann/test-issue-bot#56]
Set needs reply and verify that once we get a reply we get the label replaced.

Also, what the heck is going on with the sweeper?

**Comment by kensodemann** [comment]
This is a reply, which should result in `needs-reply` being removed and `reply-received` being applied.

**Comment by kensodemann** [comment]
```
2018-08-27T14:03:31.713390+00:00 app[web.1]:   Promise {
2018-08-27T14:03:31.713391+00:00 app[web.1]: <rejected> TypeError: Cannot read property 'payload' of undefined
2018-08-27T14:03:31.713393+00:00 app[web.1]: at issue (/app/node_modules/probot/lib/context.js:53:26)
2018-08-27T14:03:31.713394+00:00 app[web.1]: at RemoveNeedsReply.<anonymous> (/app/dist/remove-needs-reply/remove-needs-reply.js:24:51)
2018-08-27T14:03:31.713395+00:00 app[web.1]: at Generator.next (<anonymous>)
2018-08-27T14:03:31.713397+00:00 app[web.1]: at fulfilled (/app/dist/remove-needs-reply/remove-needs-reply.js:4:58)
2018-08-27T14:03:31.713398+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:68:7) }
2018-08-27T14:03:31.713399+00:00 app[web.1]: --
2018-08-27T14:03:31.713401+00:00 app[web.1]: TypeError: Cannot read property 'payload' of undefined
2018-08-27T14:03:31.713402+00:00 app[web.1]: at issue (/app/node_modules/probot/lib/context.js:53:26)
2018-08-27T14:03:31.713403+00:00 app[web.1]: at RemoveNeedsReply.<anonymous> (/app/dist/remove-needs-reply/remove-needs-reply.js:24:51)
2018-08-27T14:03:31.713404+00:00 app[web.1]: at Generator.next (<anonymous>)
2018-08-27T14:03:31.713406+00:00 app[web.1]: at fulfilled (/app/dist/remove-needs-reply/remove-needs-reply.js:4:58)
2018-08-27T14:03:31.713407+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by kensodemann** [comment]
OK, let's try another reply.
